### ISSUE TITLE
PruningModifiers invoked two times when start_epoch=0

### ISSUE THREAD

**Issue by eldarkurtic** [neuralmagic/sparseml#1090]
**Describe the bug**
When a pruning modifier has `start_epoch: 0`, it is invoked two times. The first time during the `def initialize(...)` call at https://github.com/neuralmagic/sparseml/blob/1360d075b4f61a3c536ab296dd63a87bcd577219/src/sparseml/pytorch/sparsification/pruning/modifier_pruning_base.py#L322
and the second time during the standard (expected) training-aware flow (i.e. when called from optimizer.step()).

The first call is meant to be used when modifiers are invoked in a one-shot manner only (i.e. when `epoch=inf` and `steps_per_epoch=1`).

**Expected behavior**
Pruner should be called only once when `start_epoch: 0`.

**To Reproduce**
Exact steps to reproduce the behavior: try to run any BERT-pruning example with the following recipe
```yaml
pruning_modifiers:
  - !GlobalMagnitudePruningModifier
    params:
      - re:bert.encoder.layer.*.attention.self.query.weight
      - re:bert.encoder.layer.*.attention.self.key.weight
      - re:bert.encoder.layer.*.attention.self.value.weight
      - re:bert.encoder.layer.*.attention.output.dense.weight
      - re:bert.encoder.layer.*.intermediate.dense.weight
      - re:bert.encoder.layer.*.output.dense.weight
    start_epoch: 0
    end_epoch: 2
    init_sparsity: 0.7
    final_sparsity: 0.9
    inter_func: cubic
    update_frequency: 0.5
    leave_enabled: True
    mask_type: unstructured
```

**Errors**
The pruner will be called two times at `epoch=0`, and it will prune the model two times with the same `target_sparsity`.
