### ISSUE TITLE
Enable modifiers to work with steps-based logic

### ISSUE THREAD

**Issue by eldarkurtic** [neuralmagic/sparseml#1111]
**Is your feature request related to a problem? Please describe.**
When compressing large language models, datasets for pretraining are huge and we usually can't even do one full epoch over the dataset. Hence the current logic related to SparseML modifiers (`start_epoch`, `end_epoch`, `update_frequency`) has to be manually converted by user to take into account the fact that only a fraction of training dataset will be considered during the experiment. This also makes it a bit hard and unpredictable to compose recipes, since it is not always clear when (e.g.) `update_frequency: 0.12` will trigger the corresponding modifier (rounding errors, etc.). 

An additional fact in support of this feature is that the NLP community is more used to "steps" than "epochs" terminology.

**Describe the solution you'd like**
To have a possibility to use `start_step`, `end_step`, `update_frequency` when composing recipes (in addition to the current `start_epoch`, `end_epoch` which are still very useful for CV-domain). 

For example, it would be much easier to work with a modifier that operates on `steps` like this:
```yaml
training_modifiers:
  - !EpochRangeModifier   <--- StepRangeModifier
    start_step: 0
    end_step: 1000

  - !LearningRateFunctionModifier
    start_step: 0
    end_step: 1
    lr_func: cyclic_linear
    cycle_steps: 100              <--- rewind LR every 100 steps
    init_lr: 1e-4
    final_lr: 1e-6

pruning_modifiers:
  - !MagnitudePruningModifier
    start_step: 50
    end_step: 850
    update_frequency: 50            <--- invoke modifier every 50 steps
    init_sparsity: 0.4
    target_sparsity: 0.8
```
