### ISSUE TITLE
Sparsity scheduler always follows default interpolation for GMP

### ISSUE THREAD

**Issue by eldarkurtic** [neuralmagic/sparseml#1282]
**Describe the bug**
SparseML pruning modifiers support three different interpolation functions for sparsity scheduler:
```python
    :param inter_func: the type of interpolation function to use:
        [linear, cubic, inverse_cubic]
```
but GMPruningModifier always defaults to `cubic`.
A recipe like this:
```yaml
    - !GMPruningModifier
        inter_func: linear                  <--- or `inverse_cubic`
        start_epoch: 0
        end_epoch: 40
        update_frequency: 1.0
        init_sparsity: 0.05
        final_sparsity: 0.85
        mask_type: unstructured
        params: ['sections.0.0.conv1.weight', 'sections.0.0.conv2.weight', 'sections.0.0.conv3.weight']
```
will still use `cubic` interpolation for the sparsity scheduler.

**Expected behavior**
To have GMP modifier using the correct interpolation function from the given yaml recipe.
