### ISSUE TITLE
Pruning a sparse model

### ISSUE THREAD

**Issue by eldarkurtic** [neuralmagic/sparseml#145]
**Is your feature request related to a problem? Please describe.**
As far as I understand, pruning a sparse model is not supported. For example, a common use-case is to load a pruned model, with (for example) 70% sparsity, and to prune it additionally for 20% with (for example) `GMPruningModifier`. Currently, there is no way to initialize module masks (within the `GMPruningModifier`) from this sparse checkpoint.  

**Describe the solution you'd like**
I think that having a possibility to specify in your recipe that you want to load sparsity from the checkpoint would be really useful. For example:
```yaml
  - !GMPruningModifier
    params: __ALL__
    init_sparsity: 0.05
    final_sparsity: 0.8
    start_epoch: 0.0
    end_epoch: 36.0
    update_frequency: 1.0
    load_sparsity: True
```

**Describe alternatives you've considered**
1. alternative: Currently, it's possible to define a `ConstantPruningModifier` that would hold loaded module sparsities. This is beneficial only when additional finetuning of a sparse model is needed. Sparsity information contained in the `ConstantPruningModifier` is not accessible in other pruners (for example `GMPruningModifier`) and can't be used to prune an already sparse model. 
2. alternative: One could try to bypass this issue when initializing module masks by doing something like this:
```python
self._param_mask[self._param == 0.0] = 0.0
```
in the `__init__` of `ModuleParamPruningMask`. Unfortunately, one has to modify the `sparseml` source code to achieve this and to add the explicit trigger for this in his code, for example  command-line flag `--initialize-masks-from-ckpt`.

Solving this issue in the YAML recipe has the additional benefit for users to easily reproduce their experiments by having all necessary information stored in the recipe.
