### ISSUE TITLE
AttributeError: 'GMPruningModifier' object has no attribute '_module_masks'

### ISSUE THREAD

**Issue by lhq12** [neuralmagic/sparseml#149]
Hello! I want to use sparseml to sparsify my network. But now I encountering a problem that when I set the 'lr_class' param of the LearningRateModifier as 'StepLR', an error like this will emerge: 
AttributeError: 'GMPruningModifier' object has no attribute '_module_masks'
But it works when I set the param as 'MultiStepLR' and the rest keep unchanged.

**Comment by bfineran** [comment]
Hi @lhq12 thank you for opening this issue.  Could you copy over your recipe?  This error could pop up when a section before the `GMPruningModifier ` has malformed YAML.

**Comment by lhq12** [comment]
I copied the example in the Docs and changed some lines according to the rules:
 
version: 0.1.0
modifiers:
    - !EpochRangeModifier
        start_epoch: 0.0
        end_epoch: 70.0

    - !LearningRateModifier
        start_epoch: 0
        end_epoch: -1.0
        update_frequency: -1.0
        init_lr: 0.012
        lr_class: StepLR
        lr_kwargs: {'gamma': 0.9, step: 2.0}

    - !GMPruningModifier
        start_epoch: 0
        end_epoch: 40
        update_frequency: 1.0
        init_sparsity: 0.05
        final_sparsity: 0.85
        mask_type: unstructured
        params: ['re:layer1.*.conv*', 're:layer2.*.conv*', 're:layer3.*.conv*']

**Comment by lhq12** [comment]
I copied the example in the Docs and changed some lines according to the rules:

```
version: 0.1.0
modifiers:
    - !EpochRangeModifier
        start_epoch: 0.0
        end_epoch: 70.0

    - !LearningRateModifier
        start_epoch: 0
        end_epoch: -1.0
        update_frequency: -1.0
        init_lr: 0.012
        lr_class: StepLR
        lr_kwargs: {'gamma': 0.9, step: 2.0}

    - !GMPruningModifier
        start_epoch: 0
        end_epoch: 40
        update_frequency: 1.0
        init_sparsity: 0.05
        final_sparsity: 0.85
        mask_type: unstructured
        params: ['re:layer1.*.conv*', 're:layer2.*.conv*', 're:layer3.*.conv*']
```
