### ISSUE TITLE
Resulting sparsity is 0 for all the layers

### ISSUE THREAD

**Issue by Tramtadama** [neuralmagic/sparseml#1675]
Hi,
I have tried to prune two different models, one for image regression (resnet) and another for segmentation (unet, resnet backbone).
Both after finished with pruning return 0 for all layers with tensor_sparsity(). Tried running the beans tutorial and there the pruning worked.
Here is my recipe for the segmentation:
```
# Epoch hyperparams
stabilization_epochs: 1.0
pruning_epochs: 9.0
finetuning_epochs: 5.0

# Learning rate hyperparams
init_lr: 0.0001
final_lr: 0.00005

# Pruning hyperparams
init_sparsity: 0.05
final_sparsity: 0.9

# Stabalization Stage
training_modifiers:
  - !EpochRangeModifier
    start_epoch: 0.0
    end_epoch: eval(stabilization_epochs + pruning_epochs + finetuning_epochs)

  - !SetLearningRateModifier
    start_epoch: 0.0
    learning_rate: eval(init_lr)

# Pruning Stage
pruning_modifiers:
  - !LearningRateFunctionModifier
    init_lr: eval(init_lr)
    final_lr: eval(final_lr)
    lr_func: cosine
    start_epoch: eval(stabilization_epochs)
    end_epoch: eval(stabilization_epochs + pruning_epochs)

  - !GlobalMagnitudePruningModifier
    init_sparsity: eval(init_sparsity)
    final_sparsity: eval(final_sparsity)
    start_epoch: eval(stabilization_epochs)
    end_epoch: eval(stabilization_epochs + pruning_epochs)
    update_frequency: 0.5
    params:
        - 'encoder._conv_stem.weight'
        - 'encoder._blocks.0._depthwise_conv.weight'
        - 'encoder._blocks.0._se_reduce.weight'
        - 'encoder._blocks.0._se_expand.weight'
        - 'encoder._blocks.0._project_conv.weight'
        - 'encoder._blocks.1._expand_conv.weight'
        - 'encoder._blocks.1._depthwise_conv.weight'
        - 'encoder._blocks.1._se_reduce.weight'
        - 'encoder._blocks.1._se_expand.weight'
        - 'encoder._blocks.1._project_conv.weight'
        - 'encoder._blocks.2._expand_conv.weight'
        - 'encoder._blocks.2._depthwise_conv.weight'
        - 'encoder._blocks.2._se_reduce.weight'
        - 'encoder._blocks.2._se_expand.weight'
        - 'encoder._blocks.2._project_conv.weight'
        - 'encoder._blocks.3._expand_conv.weight'
        - 'encoder._blocks.3._depthwise_conv.weight'
        - 'encoder._blocks.3._se_reduce.weight'
        - 'encoder._blocks.3._se_expand.weight'
        - 'encoder._blocks.3._project_conv.weight'
        - 'encoder._blocks.4._expand_conv.weight'
        - 'encoder._blocks.4._depthwise_conv.weight'
        - 'encoder._blocks.4._se_reduce.weight'
        - 'encoder._blocks.4._se_expand.weight'
        - 'encoder._blocks.4._project_conv.weight'
        - 'encoder._blocks.5._expand_conv.weight'
        - 'encoder._blocks.5._depthwise_conv.weight'
        - 'encoder._blocks.5._se_reduce.weight'
        - 'encoder._blocks.5._se_expand.weight'
        - 'encoder._blocks.5._project_conv.weight'
        - 'encoder._blocks.6._expand_conv.weight'
        - 'encoder._blocks.6._depthwise_conv.weight'
        - 'encoder._blocks.6._se_reduce.weight'
        - 'encoder._blocks.6._se_expand.weight'
        - 'encoder._blocks.6._project_conv.weight'
        - 'encoder._blocks.7._expand_conv.weight'
        - 'encoder._blocks.7._depthwise_conv.weight'
        - 'encoder._blocks.7._se_reduce.weight'
        - 'encoder._blocks.7._se_expand.weight'
        - 'encoder._blocks.7._project_conv.weight'
        - 'encoder._blocks.8._expand_conv.weight'
        - 'encoder._blocks.8._depthwise_conv.weight'
        - 'encoder._blocks.8._se_reduce.weight'
        - 'encoder._blocks.8._se_expand.weight'
        - 'encoder._blocks.8._project_conv.weight'
        - 'encoder._blocks.9._expand_conv.weight'
        - 'encoder._blocks.9._depthwise_conv.weight'
        - 'encoder._blocks.9._se_reduce.weight'
        - 'encoder._blocks.9._se_expand.weight'
        - 'encoder._blocks.9._project_conv.weight'
        - 'encoder._blocks.10._expand_conv.weight'
        - 'encoder._blocks.10._depthwise_conv.weight'
        - 'encoder._blocks.10._se_reduce.weight'
        - 'encoder._blocks.10._se_expand.weight'
        - 'encoder._blocks.10._project_conv.weight'
        - 'encoder._blocks.11._expand_conv.weight'
        - 'encoder._blocks.11._depthwise_conv.weight'
        - 'encoder._blocks.11._se_reduce.weight'
        - 'encoder._blocks.11._se_expand.weight'
        - 'encoder._blocks.11._project_conv.weight'
        - 'encoder._blocks.12._expand_conv.weight'
        - 'encoder._blocks.12._depthwise_conv.weight'
        - 'encoder._blocks.12._se_reduce.weight'
        - 'encoder._blocks.12._se_expand.weight'
        - 'encoder._blocks.12._project_conv.weight'
        - 'encoder._blocks.13._expand_conv.weight'
        - 'encoder._blocks.13._depthwise_conv.weight'
        - 'encoder._blocks.13._se_reduce.weight'
        - 'encoder._blocks.13._se_expand.weight'
        - 'encoder._blocks.13._project_conv.weight'
        - 'encoder._blocks.14._expand_conv.weight'
        - 'encoder._blocks.14._depthwise_conv.weight'
        - 'encoder._blocks.14._se_reduce.weight'
        - 'encoder._blocks.14._se_expand.weight'
        - 'encoder._blocks.14._project_conv.weight'
        - 'encoder._blocks.15._expand_conv.weight'
        - 'encoder._blocks.15._depthwise_conv.weight'
        - 'encoder._blocks.15._se_reduce.weight'
        - 'encoder._blocks.15._se_expand.weight'
        - 'encoder._blocks.15._project_conv.weight'
        - 'encoder._conv_head.weight'
        - 'decoder.blocks.0.conv1.0.weight'
        - 'decoder.blocks.0.conv2.0.weight'
        - 'decoder.blocks.1.conv1.0.weight'
        - 'decoder.blocks.1.conv2.0.weight'
        - 'decoder.blocks.2.conv1.0.weight'
        - 'decoder.blocks.2.conv2.0.weight'
        - 'decoder.blocks.3.conv1.0.weight'
        - 'decoder.blocks.3.conv2.0.weight'
        - 'decoder.blocks.4.conv1.0.weight'
        - 'decoder.blocks.4.conv2.0.weight'
        - 'segmentation_head.0.weight'
    leave_enabled: True

# Finetuning Stage
finetuning_modifiers:
  - !LearningRateFunctionModifier
    init_lr: eval(init_lr)
    final_lr: eval(final_lr)
    lr_func: cosine
    start_epoch: eval(stabilization_epochs + pruning_epochs)
    end_epoch: eval(stabilization_epochs + pruning_epochs + finetuning_epochs) 
```
Only things that I add to my regular code are:
```
manager = ScheduledModifierManager.from_yaml('sparsify_recipe.yaml')
optimizer = manager.modify(model, optim, steps_per_epoch=len(train_loader))
```
and at the end,
```
manager.finalize(model)
```
After that I save model with ```torch.save()``` as tar file. After loading and running ```tensor_sparsity()``` it returns 0.000 for all the layers.

Not sure if this is a bug necessarily, maybe I do something wrong that I am not aware of.

Thank you.
