### ISSUE TITLE
SparseML/YOLOv5s - ValueError: Unable to find any modifiers in given recipe.

### ISSUE THREAD

**Issue by DylDevs** [neuralmagic/sparseml#2045]
**Describe the bug**
I'm trying to train a YOLOv5s model with SparseML. (I don't know if this is important, but I am training in Google Colab). When I run train.py, I get this error:
```
ValueError: Unable to find any modifiers in given recipe.
```

**Expected behavior**
I expected the training to run successfully

**Environment**
Include all relevant environment information:
1. OS : Windows (Google Colab)
2. Python version: 3.10 (Google Colab)
3. SparseML version or commit hash: Latest
4. ML framework version(s): Latest
5. Other Python package versions: All dependencies from requirements.txt 
6. Other relevant environment information: N/A

**To Reproduce**
Run training with the recipe specified under Additional Content

**Errors**
```
ValueError: Unable to find any modifiers in given recipe. Modifiers must be listed as lists under yaml keys that include 'modifiers' in their name. Those keys and lists may also be nested under an extra key for staged recipes.
```

**Additional context**
Recipe.yaml:
```
---
layout: null
title: ETS2 vehicle Detection Dataset Recipe
---
modifiers:
    - !EpochRangeModifier
        start_epoch: 0.0
        end_epoch: 250.0

    - !SetLearningRateModifier
        start_epoch: 5.0
        learning_rate: 0.1

    - !LearningRateModifier
        start_epoch: 0.0
        end_epoch: 25.0
        lr_class: MultiStepLR
        lr_kwargs:
            gamma: 0.9
            milestones: [2.0, 5.5, 10.0]
        init_lr: 0.1

    - !GMPruningModifier
        start_epoch: 50.0
        end_epoch: 100.0
        update_frequency: 1.0
        init_sparsity: 0.05
        final_sparsity: 0.65
        params: ['blocks.1.conv']
    
    - !QuantizationModifier
        start_epoch: 100.0

    - !TrainableParamsModifier
        params: ['blocks.1.conv']

    - !SetWeightDecayModifier
        start_epoch: 5.0
        weight_decay: 0.0
    
    - !ConstantPruningModifier
        params: ['blocks.1.conv]
```

(Also, I am a complete beginner when it comes to SparseML and recipes, so i would appreciate recommendations for my recipe.) 
I am not sure what I am doing wrong with this, any help/knowledge is appreciated. Thank you for reading, have a good rest of your day.
