### ISSUE TITLE
Default quantization- True or false in SparseGPT

### ISSUE THREAD

**Issue by sriyachakravarthy** [neuralmagic/sparseml#2357]
Hi! in the recipe, if i do not want to quantize and perform structured pruning, is it okk to give quantize:false like below and do not provide QuantizationModifier in the recipe?

    SparseGPTModifier:
      sparsity: 0.5
      block_size: 128
      sequential_update: true
      quantize: false
      percdamp: 0.01
      mask_structure: "16:32"
      targets: ["re:model.layers.\\d+$"]

**Comment by rahul-tuli** [comment]
Hi @sriyachakravarthy,

Thank you for reaching out and opening an issue on SparseML!

The SparseGPTModifier no longer accepts a quantize argument, so you can safely remove it from your recipe. This will ensure that your model remains unquantized without affecting the pruning process.

Additionally, I’d recommend considering our latest framework, [LLMCompressor](https://github.com/vllm-project/llm-compressor/tree/2e0035f83b3bd56c7bfe6c497db84277ddd1dd96), which offers enhanced capabilities for model compression. If you're open to using it, the recipe would look slightly different:

```yaml
oneshot_stage:
  pruning_modifiers:
    SparseGPTModifier:
      sparsity: 0.5
      block_size: 128
      sequential_update: true
      percdamp: 0.01
      mask_structure: "16:32"
      targets: ["re:model.layers.\\d+$"]

```
