### ISSUE TITLE
Help with implementing YoloV5 and SparseML

### ISSUE THREAD

**Issue by PumeTu** [neuralmagic/sparseml#298]
Hello, 
I have been trying to implement SparseML on YoloV5, and the Readme says there is a tutorial coming soon. Would you be able to give me some tips or a small tutorial on how to implement SparseML on YoloV5?

**Comment by PumeTu** [comment]
Would you be able to let me know know by when a sample recipe would be available?

**Comment by PumeTu** [comment]
I'm also trying to quantize a library called DeepSort, would you have any suggestions or resources I could look at to quantize it? 
https://github.com/ZQPei/deep_sort_pytorch#training-the-re-id-model

**Comment by markurtz** [comment]
Hi @PumeTu, definitely. Here are some short configs for YOLOv5L that haven't been heavily optimized for performance but should get you started in the right direction. Note, for any of the other v5 variants you'll need to adjust the params listed out in the quantization modules to add or subtract appropriately.

Quantization only, run with the fine tuning hyp:
```yaml
version: 1.1.0
modifiers:
  - !EpochRangeModifier
    start_epoch: 0.0
    end_epoch: 3

  - !SetLearningRateModifier
    start_epoch: 0
    learning_rate: 0.0001

  - !SetLearningRateModifier
    start_epoch: 1
    learning_rate: 0.0032

  - !QuantizationModifier
    start_epoch: 1
    submodules:
      - model.0
      - model.1
      - model.2
      - model.3
      - model.4
      - model.5
      - model.6
      - model.7
      - model.8
      - model.9
      - model.10
      - model.11
      - model.12
      - model.13
      - model.14
      - model.15
      - model.16
      - model.17
      - model.18
      - model.19
      - model.20
      - model.21
      - model.22
      - model.23
```

Pruning only, run with the from scratch hyp:
```yaml
version: 1.1.0
modifiers:
  - !EpochRangeModifier
    start_epoch: 0.0
    end_epoch: 240.0
  - !GMPruningModifier
    params: __ALL_PRUNABLE__
    init_sparsity: 0.25
    final_sparsity: 0.90
    update_frequency: 2.0
    start_epoch: 5.0
    end_epoch: 65.0
```
