### ISSUE TITLE
GradSampler train loader error

### ISSUE THREAD

**Issue by Zeleni9** [neuralmagic/sparseml#857]
**Describe the bug**
Training yolov5 (neuralmagic branch) with recipe for sparsed model ends up with ambigous error in the GradSampler class. Error give the problem after converting <InfintieDataLoader> into <function> type and initializing GradSampler with non iterable class. Even though the check for correct type outside GradSample does not rasie Value Error in GradSampler it raises that ValueError. 

Output of the console log
```
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to drive/MyDrive/yolov5/runs/train/exp23
Starting training for 300 epochs...
Traceback (most recent call last):
  File "drive/MyDrive/yolov5/train.py", line 758, in <module>
    main(opt)
  File "drive/MyDrive/yolov5/train.py", line 654, in main
    train(opt.hyp, opt, device, callbacks)
  File "drive/MyDrive/yolov5/train.py", line 343, in train
    grid_size=gs
  File "/content/drive/MyDrive/yolov5/utils/sparse.py", line 93, in initialize
    lambda pred, target: compute_loss([p for p in pred[1]], target.to(device))[0]
  File "/usr/local/lib/python3.7/dist-packages/sparseml/pytorch/utils/sparsification.py", line 196, in __init__
    "data_loader for GradSampler must be Iterable, received object of "
ValueError: data_loader for GradSampler must be Iterable, received object of type <class 'function'>
```

**Expected behavior**
Continue to training the model with sparsified recipe for yolov5. The data format is correct and all other arguments.

**Environment**
Include all relevant environment information:
1. GoogleColab running linux
2. Python 3.7.13 [GCC 7.5.0] on linux
3. Environment create with pip install -r requirement form[ Neuralmagic yolov5 branch ](https://github.com/neuralmagic/sparseml/blob/main/integrations/ultralytics-yolov5/tutorials/sparsifying_yolov5_using_recipes.md)
4. Recipe for using sparsified training

- 
```
# General Hyperparams
num_epochs: &num_epochs 240
init_lr: &init_lr 0.01
final_lr: &final_lr 0.002
weights_warmup_lr: &weights_warmup_lr 0
biases_warmup_lr: &biases_warmup_lr 0.1

# Pruning Hyperparams
init_sparsity: &init_sparsity 0.05
pruning_start_epoch: &pruning_start_epoch 4
pruning_end_epoch: &pruning_end_epoch 100
update_frequency: &pruning_update_frequency 1.0
prune_none_target_sparsity: &prune_none_target_sparsity 0.5
prune_low_target_sparsity: &prune_low_target_sparsity 0.6
prune_mid_target_sparsity: &prune_mid_target_sparsity 0.725
prune_high_target_sparsity: &prune_high_target_sparsity 0.8

training_modifiers:
  - !EpochRangeModifier
    start_epoch: 0
    end_epoch: *num_epochs
    
  - !LearningRateFunctionModifier
    start_epoch: 3
    end_epoch: *num_epochs
    lr_func: cosine
    init_lr: *init_lr
    final_lr: *final_lr
    
  - !LearningRateFunctionModifier
    start_epoch: 0
    end_epoch: 3
    lr_func: linear
    init_lr: *weights_warmup_lr
    final_lr: *init_lr
    param_groups: [0, 1]
    
  - !LearningRateFunctionModifier
    start_epoch: 0
    end_epoch: 3
    lr_func: linear
    init_lr: *biases_warmup_lr
    final_lr: *init_lr
    param_groups: [2]
    
pruning_modifiers:
  - !GMPruningModifier
    params:
      - model.2.cv2.conv.weight
      - model.2.cv1.conv.weight
      - model.2.cv3.conv.weight
      - model.2.m.0.cv1.conv.weight
      - model.24.m.0.weight
      - model.24.m.1.weight
      - model.24.m.2.weight
    init_sparsity: *init_sparsity
    final_sparsity: *prune_none_target_sparsity
    start_epoch: *pruning_start_epoch
    end_epoch: *pruning_end_epoch
    update_frequency: *pruning_update_frequency
        
  - !GMPruningModifier
    params:
      - model.6.cv1.conv.weight
      - model.6.cv2.conv.weight
      - model.6.cv3.conv.weight
      - model.13.m.0.cv1.conv.weight
      - model.6.m.0.cv1.conv.weight
      - model.6.m.2.cv1.conv.weight
      - model.6.m.1.cv1.conv.weight
      - model.1.conv.weight
      - model.17.m.0.cv1.conv.weight
      - model.4.cv2.conv.weight
      - model.2.m.0.cv2.conv.weight
      - model.4.cv1.conv.weight
      - model.4.cv3.conv.weight
      - model.4.m.0.cv1.conv.weight
      - model.4.m.2.cv1.conv.weight
      - model.4.m.1.cv1.conv.weight
      - model.8.cv1.conv.weight
    init_sparsity: *init_sparsity
    final_sparsity: *prune_low_target_sparsity
    start_epoch: *pruning_start_epoch
    end_epoch: *pruning_end_epoch
    update_frequency: *pruning_update_frequency
        
  - !GMPruningModifier
    params:
      - model.9.cv3.conv.weight
      - model.6.m.2.cv2.conv.weight
      - model.5.conv.weight
      - model.9.cv1.conv.weight
      - model.6.m.1.cv2.conv.weight
      - model.6.m.0.cv2.conv.weight
      - model.17.m.0.cv2.conv.weight
      - model.9.cv2.conv.weight
      - model.10.conv.weight
      - model.13.cv2.conv.weight
      - model.9.m.0.cv1.conv.weight
      - model.20.m.0.cv1.conv.weight
      - model.13.cv3.conv.weight
      - model.13.cv1.conv.weight
      - model.17.cv3.conv.weight
      - model.14.conv.weight
      - model.4.m.2.cv2.conv.weight
      - model.3.conv.weight
      - model.4.m.1.cv2.conv.weight
      - model.4.m.0.cv2.conv.weight
      - model.17.cv1.conv.weight
      - model.23.m.0.cv1.conv.weight
      - model.20.cv1.conv.weight
      - model.23.cv1.conv.weight
    init_sparsity: *init_sparsity
    final_sparsity: *prune_mid_target_sparsity
    start_epoch: *pruning_start_epoch
    end_epoch: *pruning_end_epoch
    update_frequency: *pruning_update_frequency
        
  - !GMPruningModifier
    params:
      - model.23.m.0.cv2.conv.weight
      - model.21.conv.weight
      - model.23.cv3.conv.weight
      - model.23.cv2.conv.weight
      - model.20.m.0.cv2.conv.weight
      - model.18.conv.weight
      - model.9.m.0.cv2.conv.weight
      - model.7.conv.weight
      - model.20.cv3.conv.weight
      - model.20.cv2.conv.weight
      - model.8.cv2.conv.weight
      - model.13.m.0.cv2.conv.weight
      - model.17.cv2.conv.weight
    init_sparsity: *init_sparsity
    final_sparsity: *prune_high_target_sparsity
    start_epoch: *pruning_start_epoch
    end_epoch: *pruning_end_epoch
    update_frequency: *pruning_update_frequency
```

**Errors**
```
  File "/content/drive/MyDrive/yolov5/utils/sparse.py", line 93, in initialize
    lambda pred, target: compute_loss([p for p in pred[1]], target.to(device))[0]
  File "/usr/local/lib/python3.7/dist-packages/sparseml/pytorch/utils/sparsification.py", line 196, in __init__
    "data_loader for GradSampler must be Iterable, received object of "
ValueError: data_loader for GradSampler must be Iterable, received object of type <class 'function'>

```
