### ISSUE TITLE
Attributes which depend on epoch are missed when composing stages

### ISSUE THREAD

**Issue by eldarkurtic** [neuralmagic/sparseml#972]
**Describe the bug**
Some modifiers (e.g. `QuantizationModifier`) have attributes that depend on epoch (e.g. `disable_quantization_observer_epoch`) and these attributes are not incremented when composing stages.

**Expected behavior**
To increment those attributes too, just as `start_epoch` and `end_epoch` are incremented.

**Errors**

```yaml
      - !QuantizationModifier
          activation_bits: 8
          disable_quantization_observer_epoch: 1.0             <--- missed increment
          end_epoch: -1.0
          exclude_batchnorm: True
          exclude_module_types: ['LayerNorm', 'BatchNorm1d', 'BatchNorm2d', 'BatchNorm3d']
          model_fuse_fn_name: conv_bn_relus
          quantize_conv_activations: True
          quantize_embedding_activations: False
          quantize_embeddings: True
          quantize_linear_activations: False
          reduce_range: False
          start_epoch: 30.0                                    <--- correctly incremented
          submodules: ['qa_outputs', 'bert.embeddings', 'bert.encoder']
          tensorrt: False
          weight_bits: 8
```
